# RedHat related OSs
- name: create epel.repo
  action: template src=ganglia/templates/epel.repo dest=/etc/yum.repos.d/epel.repo 
  when: redhat_os

- name: Yum install {{ item }}
  action: yum pkg={{ item }} state=installed
  with_items:
    - ganglia-gmond
    - ganglia-gmetad
  when: redhat_os

- name: configure gmond (REL6)
  action: template src=ganglia/templates/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond
  when: redhat_os and {{ ansible_distribution_version|float }} >= 6

- name: configure gmond (REL5)
  action: template src=ganglia/templates/gmond.old.conf dest=/etc/gmond.conf owner=root group=root
  notify:
      - restart gmond
  when: redhat_os and {{ ansible_distribution_version|float }} < 6
      
- name: start gmond
  action: service name=gmond state=running
  when: redhat_os
  
- name: configure gmetad (REL5)
  action: template src=ganglia/templates/gmetad.conf dest=/etc/gmetad.conf owner=root group=root
  notify:
      - restart gmetad
  when: redhat_os and {{ ansible_distribution_version|float }} < 6
  
- name: configure gmetad (REL6)
  action: template src=ganglia/templates/gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root group=root
  notify:
      - restart gmetad
  when: redhat_os and {{ ansible_distribution_version|float }} >= 6
  
- name: start gmetad
  action: service name=gmetad state=running
  when: redhat_os

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed
  with_items:
    - ganglia-monitor
    - gmetad
  when: debian_os
  
- name: configure ganglia-monitor
  action: template src=ganglia/templates/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart ganglia-monitor
  when: debian_os
  
- name: configure gmetad
  action: template src=ganglia/templates/gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root group=root
  notify:
      - restart gmetad-dev
  when: debian_os
  
# Open the gmetad port
- name: Open the gmetad port
  action: shell /sbin/iptables -I INPUT -p tcp --dport 8651 -j ACCEPT

- name: Open the access gmond port
  action: shell /sbin/iptables -I INPUT -p udp --dport 8649 -j ACCEPT
